-- Personal settings the config reads when they exist, kept out of version
-- control. To use: copy this file to local.lua in the same directory
-- (local.lua is gitignored) and fill in what you want. Every key is optional,
-- and the config works the same with no file at all.
--
-- These are the personal, machine-side knobs. A project that wants to carry
-- its own editor config does it the standard way instead: 'exrc' is on, so a
-- trusted .nvim.lua in the project (or any directory above it) runs after
-- this config and can tweak Neovim directly; vim.lsp.config() calls there
-- merge over the defaults lua/mivn/lsp.lua ships.
return {
  -- Per-server tuning, one entry per nvim-lspconfig name. mise installs the
  -- servers; this is only how they are configured once they are there.
  -- `false` turns one off, which matters when the binary is installed for
  -- other reasons and keeps attaching. A table carries the finer knobs, all
  -- optional:
  --
  --   path      an executable of your own, instead of the one PATH
  --             resolves. It is also what proves the server is installed,
  --             so naming a server lua/mivn/lsp.lua's table does not carry
  --             adds it.
  --
  --   config    handed to vim.lsp.config(<name>, ...) and deep-merged over
  --             the defaults the config ships, so a key here wins and
  --             everything else keeps its default. This is the full config
  --             shape (settings, init_options, cmd_env, ...), because
  --             servers differ in where they read configuration from. Note
  --             the nesting under `settings` follows each server's own
  --             schema, and the section name in there is the server's, not
  --             mivn's: gopls reads settings.gopls, lua_ls reads
  --             settings.Lua.
  --
  --   probe     how :checkhealth mivn asks this server's binary for its
  --             version: the extra arguments as a list, or false for a
  --             binary with no harmless one-shot flag, which is then only
  --             looked up and never run.
  --
  --   sandbox   false runs this server unconfined. lua/mivn/sandbox.lua
  --             says what it is confined to otherwise, and why.
  --
  --   prefixes  gopls only: the Go import prefixes that count as "ours",
  --             as a list. Each prefix earns a gci block of its own, in
  --             list order, plus gopls' `local` treatment. Different
  --             checkouts want different prefixes, so this one usually
  --             lives under `projects` below.
  --
  -- This file is machine-side: `false` here turns a server off everywhere.
  -- Per-project exceptions are the project's own business, and its trusted
  -- .nvim.lua makes them the stock way, after this config has run. Off in
  -- one project:
  --
  --   vim.lsp.enable("gopls", false)
  --
  -- Or the other direction: on in one project, with the project's own
  -- config and binary, even for a server this file turned off or one mivn
  -- never knew:
  --
  --   vim.lsp.config("ty", { cmd = { "/opt/ty/bin/ty", "server" } })
  --   vim.lsp.enable("ty")
  --
  -- Leave the cmd out and the binary resolves from PATH as stock Neovim
  -- would.
  --
  -- :checkhealth mivn shows the merged result. For example:
  --
  --   lsp = {
  --     marksman = false, -- markdown needs no server on this machine
  --     ty = { path = "/some/path/ty" },    -- my own ty, not mise's
  --     basedpyright = { path = "basedpyright", probe = { "--version" } },
  --     gopls = {
  --       prefixes = { "github.com/my-org/" },
  --       config = {
  --         settings = { gopls = { buildFlags = { "-tags=integration" } } },
  --       },
  --     },
  --   },
  lsp = {},

  -- Changes to the tree-sitter grammar list in lua/mivn/treesitter.lua:
  -- grammar name to true (add) or false (drop). Takes effect on the next
  -- :MivnInstallGrammars run. For example:
  --
  --   treesitter_grammars = {
  --     ocaml = true,
  --     zig = false,
  --   },
  treesitter_grammars = {},

  -- Everything above is global. `projects` scopes any of the same keys to a
  -- directory: when Neovim starts inside one, that directory's values merge
  -- over the globals, and the longest matching directory wins. Merging goes
  -- per key and then per entry (per server, per grammar), and there it
  -- stops: a server's entry here replaces the global one whole rather than
  -- deep-merging into it, so what a project states is exactly what applies.
  -- One client's checkouts can carry their own import prefixes and a
  -- different Elixir server, for example:
  --
  --   projects = {
  --     ["~/work/client-a"] = {
  --       lsp = {
  --         gopls = { prefixes = { "github.com/client-a/" } },
  --         expert = false,
  --         elixirls = { path = "elixir-ls" },
  --       },
  --     },
  --   },
  projects = {},
}
